<?php declare(strict_types=1);

namespace Survos\CodeBundle\Command;

use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Attribute\AdminDashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\Assets;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PsrPrinter;
use Survos\EzBundle\Controller\BaseCrudController;
use Survos\MeiliBundle\Bridge\EasyAdmin\MeiliEasyAdminMenuFactory;
use Survos\MeiliBundle\Service\MeiliService;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Attribute\Option;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

#[AsCommand(name: 'code:meili:admin', description: 'Generate MeiliDashboardController and CRUD controllers')]
class MeiliAdminCommand extends Command
{
    public function __construct(private readonly ?MeiliService $meiliService=null)
    {
        parent::__construct();
    }

    public function __invoke(
        SymfonyStyle $io,
        #[Option("Overwrite existing files")] bool $force=false,
        #[Option("define the route name", name: 'route')] string $dashboardRouteName='meili_admin',
        #[Option("define the path")] string $path = '/ez-meili',
    ): int
    {

        $fs = new Filesystem();
        $dir = 'src/Controller/Admin';
        $fs->mkdir($dir);

        // -- Generate MeiliDashboardController
        $file = new PhpFile();
        $ns = $file->addNamespace('App\\Controller\\Admin');
        foreach ([
                     Dashboard::class,
                     MenuItem::class,
                     AbstractDashboardController::class,
                     MeiliService::class,
                     EntityManagerInterface::class,
                     UrlGeneratorInterface::class,
                     Response::class,
                     MeiliEasyAdminMenuFactory::class,
                     AdminDashboard::class,
                 ] as $class) {
            $ns->addUse($class);
        }

        $class = $ns->addClass('MeiliDashboardController')
            ->setExtends(AbstractDashboardController::class)
            ->addComment('Generated by code:meili:admin');

        // #[AdminDashboard(routePath: '/', routeName: 'admin')]
        $class->addAttribute(AdminDashboard::class, [
            $path, $dashboardRouteName
        ]);

//        $class->addProperty('em')->setPrivate();
//        $class->addProperty('meiliService')->setPrivate();
//        $class->addProperty('urlGenerator')->setPrivate();

        $constructor = $class->addMethod('__construct');
        foreach ([
                     EntityManagerInterface::class => 'em',
                     UrlGeneratorInterface::class => 'urlGenerator',
                    MeiliEasyAdminMenuFactory::class => 'meiliMenuFactory',
                     MeiliService::class => 'meiliService',
                 ] as $className => $parameterName) {
        $constructor
            ->addPromotedParameter($parameterName)
            ->setPrivate()
            ->setReadOnly()
            ->setType($className);
        }

//        $method = $class->addMethod('__construct')
//            ->setBody('$this->em = $em; $this->meiliService = $meiliService; $this->urlGenerator = $urlGenerator;');
//
//        $method
//            ->addParameter('em')->setType('EntityManagerInterface');
//        $method
//            ->addParameter('meiliService')->setType(MeiliService::class);
//            $method
//            ->addParameter('urlGenerator')->setType(UrlGeneratorInterface::class);

        $index = $class->addMethod('index')
            ->setReturnType(Response::class)
            ->setBody('return $this->render("@SurvosMeili/ez/dashboard.html.twig", ["settings" => $this->meiliService->settings]);');

        $configureDashboard = $class->addMethod('configureDashboard')
            ->setReturnType(Dashboard::class)
            ->setBody('return Dashboard::new()->setTitle("Meili Dashboard");');

        $class->addMethod('configureAssets')
            ->setReturnType(Assets::class)
            ->setBody('return Assets::new()->useCustomIconSet();');

        $configureMenu = $class->addMethod('configureMenuItems')
            ->setReturnType('iterable')
            ->setBody($this->generateMenuBody());

        $method = $class->addMethod('getSemanticSearchItems');
        $method->addParameter('indexName')->setType('string');
        $method->addParameter('meiliSetting')->setType('array');
        $method->setReturnType('array')
            ->setBody(<<<'PHP'
        $items = [];

        if (!empty($meiliSetting['embedders'])) {
            foreach ($meiliSetting['embedders'] as $embedder) {
                $items[] = MenuItem::linkToUrl(
                    'Semantic: ' . ucfirst(str_replace('_', ' ', $embedder)),
                    'fas fa-brain',
                    $this->urlGenerator->generate('meili_insta_embed',
                        ['indexName' => $indexName, 'embedder' => $embedder]
                    )
                )->setLinkTarget('_blank');
                ;
            }
        }

        return $items;
PHP
);

        $printer = new PsrPrinter();
        $output = "$dir/MeiliDashboardController.php";
        if (!file_exists($output) || $force) {
            $fs->dumpFile($output, $printer->printFile($file));
            $io->writeln("<info>Generated $dir/MeiliDashboardController.php</info>");
        }
        // -- Generate CRUD controllers for each Meili index
            foreach ($this->meiliService->getRawIndexSettings() as $indexName => $meiliSetting) {
                $jsTemplateFile = sprintf('templates/js/%s.html.twig', $meiliSetting['rawName']);
                if (!file_exists($jsTemplateFile)) {
                    $jsTemplateDir = dirname($jsTemplateFile);
                    if (!file_exists($jsTemplateDir)) {
                        if (!mkdir($jsTemplateDir, 0777, true) && !is_dir($jsTemplateDir)) {
                            throw new \RuntimeException(sprintf('Directory "%s" was not created', $dir));
                        }
                    }
                    // this was before we had a smart, generic template
//                    $template = __DIR__ . '/../../twig/js/detail.html.twig';
//                    // we really need to render this with the variables, set up the shape, etc.
//                    assert(file_exists($template), "Missing $template template");
//                    file_put_contents($jsTemplateFile, file_get_contents($template));
                }

                $className = new \ReflectionClass($meiliSetting['class'])->getShortName();
                $crudFile = new PhpFile();
                $ns2 = $crudFile->addNamespace('App\\Controller\\Admin');
                $ns2->addUse(BaseCrudController::class);
                $crud = $ns2->addClass($className . 'CrudController')
                    ->setExtends(BaseCrudController::class);
                $crud->addMethod('getEntityFqcn')
                    ->setStatic()
                    ->setReturnType('string')
                    ->setBody("return \\{$meiliSetting['class']}::class;");

                $entityCrud = "$dir/{$className}CrudController.php";
                if (!file_exists($entityCrud) || $force) {
                    $fs->dumpFile($entityCrud, $printer->printFile($crudFile));
                    $io->writeln("<info>Generated $entityCrud for $className</info>");
                }
            }

        return Command::SUCCESS;
    }

    private function generateMenuBody(): string
    {
        return <<<'PHP'
        // Main navigation
        yield MenuItem::linkToDashboard('Dashboard', 'fa fa-home');
//        yield MenuItem::linkToRoute('Examples', 'fa fa-lightbulb', 'admin_examples');

        yield MenuItem::section('Content Management', 'fas fa-folder-open');
        yield from $this->meiliMenuFactory->createIndexMenus();

        // Group each entity with its search options
        // Optional: Add a tools/utilities section at the bottom
        yield MenuItem::section('Tools', 'fas fa-wrench');
        foreach ($this->meiliService->tools as $tool) {
            yield MenuItem::linkToUrl($tool['label'], 'fas fa-chart-line', $tool['url']);
        }

        yield MenuItem::linkToUrl('Search Analytics', 'fas fa-chart-line', '#')
            ->setPermission('ROLE_ADMIN');
PHP;
    }
}

