<?php declare(strict_types=1);

namespace Survos\CodeBundle\Command;

use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Attribute\AdminDashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PsrPrinter;
use Survos\MeiliBundle\Service\MeiliService;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

#[AsCommand(name: 'code:meili:admin', description: 'Generate MeiliDashboardController and CRUD controllers')]
class MeiliAdminCommand extends Command
{
    public function __construct(private readonly ?MeiliService $meiliService=null)
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $fs = new Filesystem();
        $dir = 'src/Controller/Admin';
        $fs->mkdir($dir);

        // -- Generate MeiliDashboardController
        $file = new PhpFile();
        $ns = $file->addNamespace('App\\Controller\\Admin');
        foreach ([
                     Dashboard::class,
                     MenuItem::class,
                     AbstractDashboardController::class,
                     MeiliService::class,
                     EntityManagerInterface::class,
                     UrlGeneratorInterface::class,
                     Response::class,
                     AdminDashboard::class,
                 ] as $class) {
            $ns->addUse($class);
        }

        $class = $ns->addClass('MeiliDashboardController')
            ->setExtends(AbstractDashboardController::class)
            ->addComment('Generated by code:meili:admin');

        // #[AdminDashboard(routePath: '/', routeName: 'admin')]
        $class->addAttribute(AdminDashboard::class, [
            '/ez-meili', 'ez_meili'
        ]);

//        $class->addProperty('em')->setPrivate();
//        $class->addProperty('meiliService')->setPrivate();
//        $class->addProperty('urlGenerator')->setPrivate();

        $constructor = $class->addMethod('__construct');
        foreach ([
                     EntityManagerInterface::class => 'em',
                     UrlGeneratorInterface::class => 'urlGenerator',
                     MeiliService::class => 'meiliService',
                 ] as $className => $parameterName) {
        $constructor
            ->addPromotedParameter($parameterName)
            ->setPrivate()
            ->setReadOnly()
            ->setType($className);
        }

//        $method = $class->addMethod('__construct')
//            ->setBody('$this->em = $em; $this->meiliService = $meiliService; $this->urlGenerator = $urlGenerator;');
//
//        $method
//            ->addParameter('em')->setType('EntityManagerInterface');
//        $method
//            ->addParameter('meiliService')->setType(MeiliService::class);
//            $method
//            ->addParameter('urlGenerator')->setType(UrlGeneratorInterface::class);

        $index = $class->addMethod('index')
            ->setReturnType(Response::class)
            ->setBody('return $this->render("@SurvosMeili/ez/dashboard.html.twig", ["settings" => $this->meiliService->settings]);');

        $configureDashboard = $class->addMethod('configureDashboard')
            ->setReturnType(Dashboard::class)
            ->setBody('return Dashboard::new()->setTitle("Meili Dashboard");');

        $configureMenu = $class->addMethod('configureMenuItems')
            ->setReturnType('iterable')
            ->setBody($this->generateMenuBody());

        $printer = new PsrPrinter();
        $fs->dumpFile("$dir/MeiliDashboardController.php", $printer->printFile($file));
        $output->writeln("<info>Generated $dir/MeiliDashboardController.php</info>");

        // -- Generate CRUD controllers for each Meili index
            foreach ($this->meiliService->settings as $indexName => $meiliSetting) {
                $className = (new \ReflectionClass($meiliSetting['class']))->getShortName();
                $crudFile = new PhpFile();
                $ns2 = $crudFile->addNamespace('App\\Controller\\Admin');
                $ns2->addUse(AbstractCrudController::class);
                $crud = $ns2->addClass($className . 'CrudController')
                    ->setExtends(AbstractCrudController::class);
                $crud->addMethod('getEntityFqcn')
                    ->setStatic()
                    ->setReturnType('string')
                    ->setBody("return \\{$meiliSetting['class']}::class;");

                $entityCrud = "$dir/{$className}CrudController.php";
                if (!file_exists($entityCrud)) {
                    $fs->dumpFile($entityCrud, $printer->printFile($crudFile));
                    $output->writeln("<info>Generated $entityCrud for $className</info>");
                }
            }

        return Command::SUCCESS;
    }

    private function generateMenuBody(): string
    {
        return <<<'PHP'
yield MenuItem::linkToDashboard('Dashboard', 'fa fa-home');
foreach ($this->meiliService->settings as $indexName => $meiliSetting) {
    $class = $meiliSetting['class'];
    $label = (new \ReflectionClass($class))->getShortName();
    yield MenuItem::linkToCrud($label, 'fas fa-database', $class)
        ->setBadge($this->em->getRepository($class)->count());
}
PHP;
    }
}

