<?php declare(strict_types=1);

namespace Survos\CodeBundle\Command;

use EasyCorp\Bundle\EasyAdminBundle\Attribute\AdminDashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\Assets;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use Nette\PhpGenerator\Literal;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PsrPrinter;
use Survos\CoreBundle\Entity\RouteParametersInterface;
use Survos\EzBundle\Controller\AbstractEzCrudController;
use Survos\EzBundle\Field\LinkedTextField;
use Survos\MeiliBundle\Controller\AbstractMeiliController;
use Survos\MeiliBundle\Service\MeiliService;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Attribute\Option;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

#[AsCommand(name: 'code:meili:admin', description: 'Generate MeiliDashboardController and CRUD controllers')]
class MeiliAdminCommand extends Command
{
    public function __construct(private readonly ?MeiliService $meiliService = null)
    {
        parent::__construct();
    }

    public function __invoke(
        SymfonyStyle $io,
        #[Option('Overwrite existing files')] bool $force = false,
        #[Option('define the route name', name: 'route')] string $dashboardRouteName = 'meili_admin',
        #[Option('define the path')] string $path = '/ez-meili',
    ): int {
        if (!$this->meiliService) {
            $io->error('MeiliService is not available; cannot generate CRUDs/dashboard.');
            return Command::FAILURE;
        }

        $fs = new Filesystem();

        // Generate assets/admin.js (dedicated EA entrypoint)
        $fs->mkdir('assets');
        $adminJs = 'assets/admin.js';
        if (!$fs->exists($adminJs) || $force) {
            $fs->dumpFile($adminJs, <<<'JS'
/**
 * EasyAdmin entrypoint (separate from app.js) to avoid bootstrap/tabler collisions
 * and ensure Stimulus + Symfony UX components load as expected.
 */
import './stimulus_bootstrap.js';

// Optional: JSON viewer (requires importmap/npm dependency)
// import "@andypf/json-viewer";
JS
            );
            $io->writeln("<info>Generated $adminJs</info>");
        } else {
            $io->writeln("<comment>skip</comment> $adminJs (exists; use --force)");
        }

        $dir = 'src/Controller/Admin';
        $fs->mkdir($dir);

        $printer = new PsrPrinter();

        // ---------------------------
        // Dashboard: lean controller
        // ---------------------------
        $dashboardFile = new PhpFile();
        $ns = $dashboardFile->addNamespace('App\\Controller\\Admin');

        foreach ([
            AdminDashboard::class,
            Assets::class,
            Dashboard::class,
            AbstractMeiliController::class,
        ] as $class) {
            $ns->addUse($class);
        }

        $dashClass = $ns->addClass('MeiliDashboardController')
            ->setFinal()
            ->setExtends(AbstractMeiliController::class)
            ->addComment('Generated by code:meili:admin');

        $dashClass->addConstant('MEILI_ROUTE', $dashboardRouteName)->setPublic();

        $dashClass->addAttribute(AdminDashboard::class, [$path, new Literal('self::MEILI_ROUTE')]);

        $dashClass->addMethod('configureDashboard')
            ->setPublic()
            ->setReturnType(Dashboard::class)
            ->setBody(<<<'PHP'
return parent::configureDashboard()
    ->setTitle('Meili Admin');
PHP);

        // Ensure EasyAdmin loads the dedicated entrypoint
        $dashClass->addMethod('configureAssets')
            ->setPublic()
            ->setReturnType(Assets::class)
            ->setBody(<<<'PHP'
return parent::configureAssets()
    ->addAssetMapperEntry('admin');
PHP);

        $dashboardOutput = "$dir/MeiliDashboardController.php";
        if (!file_exists($dashboardOutput) || $force) {
            $fs->dumpFile($dashboardOutput, $printer->printFile($dashboardFile));
            $io->writeln("<info>Generated $dashboardOutput</info>");
        } else {
            $io->writeln("<comment>skip</comment> $dashboardOutput (exists; use --force)");
        }

        // -----------------------------------------
        // CRUD controllers for each Meili index
        // -----------------------------------------
        foreach ($this->meiliService->getRawIndexSettings() as $indexName => $meiliSetting) {
            // keep your template directory scaffolding
            $jsTemplateFile = sprintf('templates/js/%s.html.twig', $meiliSetting['rawName']);
            if (!file_exists($jsTemplateFile)) {
                $jsTemplateDir = dirname($jsTemplateFile);
                if (!is_dir($jsTemplateDir) && !@mkdir($jsTemplateDir, 0777, true) && !is_dir($jsTemplateDir)) {
                    throw new \RuntimeException(sprintf('Directory "%s" was not created', $jsTemplateDir));
                }
            }

            $entityFqcn = (string)$meiliSetting['class'];
            $ref = new \ReflectionClass($entityFqcn);
            $short = $ref->getShortName();

            $crudFile = new PhpFile();
            $ns2 = $crudFile->addNamespace('App\\Controller\\Admin');

            $ns2->addUse(AbstractEzCrudController::class);
            $ns2->addUse(Crud::class);
            $ns2->addUse(LinkedTextField::class);
            $ns2->addUse($entityFqcn);

            if ($ref->implementsInterface(RouteParametersInterface::class)) {
                $ns2->addUse(RouteParametersInterface::class);
            }

            $crudClass = $ns2->addClass($short . 'CrudController')
                ->setFinal()
                ->setExtends(AbstractEzCrudController::class)
                ->addComment('Generated by code:meili:admin');

            $crudClass->addMethod('getEntityFqcn')
                ->setStatic()
                ->setPublic()
                ->setReturnType('string')
                ->setBody("return \\{$entityFqcn}::class;");

            [$linkField, $paramName, $paramProp] = $this->guessLinking($ref);

            if ($linkField) {
                $crudClass->addConstant('SHOW_ROUTE', 'admin_app_' . strtolower($short) . '_show')
                    ->addComment('TODO: adjust SHOW_ROUTE to your app show route');

                $method = $crudClass->addMethod('preferredFields')
                    ->setProtected()
                    ->setReturnType('iterable');
                $method
                    ->addParameter('pageName')->setType('string');
                $method
                    ->setBody(sprintf(<<<'PHP'
if ($pageName !== Crud::PAGE_INDEX) {
    return [];
}

yield LinkedTextField::new('%s', '%s')
    ->setRoute(self::SHOW_ROUTE, '%s', '%s');
PHP, $linkField, ucfirst($linkField), $paramName, $paramProp));
            }

            $entityCrud = "$dir/{$short}CrudController.php";
            if (!file_exists($entityCrud) || $force) {
                $fs->dumpFile($entityCrud, $printer->printFile($crudFile));
                $io->writeln("<info>Generated $entityCrud for $short</info>");
            } else {
                $io->writeln("<comment>skip</comment> $entityCrud (exists; use --force)");
            }
        }

        return Command::SUCCESS;
    }

    private function guessLinking(\ReflectionClass $ref): array
    {
        $props = array_map(
            static fn(\ReflectionProperty $p) => $p->getName(),
            $ref->getProperties()
        );

        $candidates = ['title','name','label','officialName','sku','code','id'];
        $linkField = null;
        foreach ($candidates as $c) {
            if (\in_array($c, $props, true)) {
                $linkField = $c;
                break;
            }
        }

        $paramName = 'id';
        $paramProp = 'id';

        if ($ref->implementsInterface(RouteParametersInterface::class) && $ref->hasConstant('UNIQUE_PARAMETERS')) {
            $map = $ref->getConstant('UNIQUE_PARAMETERS');
            if (\is_array($map) && $map) {
                $k = array_key_first($map);
                $v = $map[$k] ?? null;
                if (\is_string($k) && \is_string($v)) {
                    $paramName = $k;
                    $paramProp = $v;
                }
            }
        } else {
            if (!\in_array('id', $props, true) && \in_array('sku', $props, true)) {
                $paramProp = 'sku';
            }
        }

        return [$linkField, $paramName, $paramProp];
    }
}
